config/routes.rb
Rails.application.routes.draw do

  resources :subjects
  resources :pages
  resources :sections
 

  root "subjects#index"

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
 
 # To configure a different table name
 #self.table_name = "admin_users"

 has_and_belongs_to_many :pages
 has_many :section_edits
 has_many :sections, :through => :section_edits

end

app/models/page.rb
class Page < ActiveRecord::Base

	belongs_to :subject
	has_and_belongs_to_many :editors, :class_name => "AdminUser"
	#this creates and alias & specifies that when we say 'editors' we are refering to the class AdminUser
	
	scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("pages.position ASC") }
  scope :newest_first, lambda {order("pages.created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

end

app/models/section.rb
class Section < ActiveRecord::Base

	has_many :section_edits
	has_many :editors, :through => :section_edits, :class_name => "AdminUser"

	scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("sections.position ASC") }
  scope :newest_first, lambda {order("sections.created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

end

app/models/section_edit.rb
 class SectionEdit < ActiveRecord::Base

	belongs_to :editor, :class_name => "AdminUser", :foreign_key => "admin_user_id"
	belongs_to :section

end

app/models/subject.rb
class Subject < ActiveRecord::Base

	has_many :pages

	scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :sorted, lambda { order("subjects.position ASC") }
  scope :newest_first, lambda {order("subjects.created_at DESC")}
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

end

# % are wild cards, so %query% doesn't have to match exactly - it can be a substring

# ! IMPORTANT ! a scope is the same as writing:

# def self.visible
# 	where (:visible => true)
# end

# or 

# def self.sorted
# 	order ("subject.position ASC")
# end

# lambda's are evaluated when called, each time they are called
# so if you are doing something with time/date it's best to use lambda 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  
  layout false

  def index
  end

  def hello
  	@array = [1,2,3,4,5]
  	render ('hello')
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
layout "admin"

  def index
  	@pages = Page.sorted
  end

  def show
  	@page = Page.find(params[:id])
  end

  def new
  	@page = Page.new
  end

  def create
  	@page = Page.new(page_params)
  	if @page.save
  		flash[:notice] = "#{@page.name} created successfully"
  		redirect_to pages_path
  	else
  		render :new
  	end
  end

  def edit
  	@page = Page.find(params[:id])
  end

  def update
  	@page = Page.find(params[:id])
  	if @page.update(page_params)
  		flash[:notice] = "#{@page.name} updated successfully"
  		redirect_to pages_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@page.find(params[:id])
  	@page.destroy
  	flash[:notice] = "#{@page.name} destroyed successfully"
  	redirect_to pages_path
  end

private
	def page_params
		params.require(:page).permit(:subject_id, :name, :permalink, :position, :visible)
	end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
	layout "admin"

  def index
  	@sections = Section.sorted
  end

  def show
  	@section = Section.find(params[:id])
  end

  def new
  	@section = Section.new({:name => "Enter Name"})
  end

  def create
  	@section = Section.new
  	if @section.save(section_params)
  		flash[:notice] = "#{@section.name} created successfully"
      #if save succeeds redirect to index
  		redirect_to sections_path
  	else
  		render :new
  	end
  end

  def edit
  	@section = Section.find(params[:id])
  end

  def update
  	@section = Section.find(params[:id])
  	if @section.update(section_params)
  		flash[:notice] = "#{@section.name} updated successfully"
  		redirect_to sections_path
  	else
  		render :edit
  	end
	end

  def destroy
  	@section = Section.find(params[:id])
  	@section.destroy
  	flash[:notice] = "#{@section.name} destroyed successfully"
  	redirect_to sections_path
  end

  private
	  def section_params
	  	params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content)
	  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  layout "admin"

  def index
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => "Enter Name"})
  end

  def create
    #instantiate a new object using params from the form
    @subject = Subject.new(subject_params)
    #save the object
    if @subject.save
      flash[:notice] = "#{@subject.name} created successfully"
      #if save succeeds redirect to index
      redirect_to subjects_path
    else
      #if save fails, redisplay form so user can fix problems
      render  :new
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    #find an existing object using id
    @subject = Subject.find(params[:id])
    #update subject
    if @subject.update(subject_params)
      #if update succeeds redirect to index
      flash[:notice] = "#{@subject.name} updated successfully"
      redirect_to subjects_path
    else
      #if update fails, redisplay edit form so user can fix problems
      render  :edit
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "#{@subject.name} deleted successfully"
    redirect_to subjects_path
  end

  private

    def subject_params
      params.require(:subject).permit(:name, :position, :visible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def status_tag(boolean, options={})
		options[:true_text] ||=''
		options[:false_text] ||=''

		if boolean
			content_tag(:span, options[:true_text], :class => 'status true')
		else
			content_tag(:span, options[:false_text], :class => 'status false')
		end
	end

end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/demos/hello.html.erb
<h1>Demos#hello</h1>
<p>This is the Hello page!</p>

<% a = [4, 5, 6] %>
<p><%= a[0] + a[2] %></p>
<br/>
<% @array.each do |n|%>
<%= n %>
<%end%>

<a href= '/demos/index'>Index page 1</a><br/>
<%= link_to("Index page 2", {:controller => 'demos', :action => 'index'}) %>

app/views/demos/index.html.erb
<h1>Demos#index</h1>
<p>This is the Demos index page!</p>

<a href= '/demos/hello'>Hello page 1</a><br/>
<%= link_to("Hello page 2", {:controller => 'demos', :action => 'hello'}) %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple CMS | <%= @page_title || "Admin" %></title>
  <!-- %= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true % -->
  <%# = javascript_include_tag #'application', 'data-turbolinks-track' => true %>
  <%# = csrf_meta_tags %>

  <style>
  	span.status { display: block; width: 10px; height: 10px; margin: 0.25em auto; padding: 0; border: 1px solid #000000; }
  	span.status.true { background: green; color: green; }
  	span.status.false { background: red; color: red; }
  </style>

</head>
<body>
	<div id="header">
		<h2>Simple CMS Admin</h2>
	</div>

	<div id="main">
	  <% if !flash[:notice].blank? %>
			<div class="notice">
				<h3><%= flash[:notice] %></h3>
			</div>
		<% end %>
		<div id="content">
			<!-- before yield -->
			<%= yield %>
			<!-- after yeild -->
		</div>
	</div>

	<div id="footer">
		<p id="copyright">&copy; Ellen Stucki</p>
	</div>  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple CMS</title>
  <!-- %= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true % -->
  <%# = javascript_include_tag #'application', 'data-turbolinks-track' => true %>
  <%# = csrf_meta_tags %>

</head>
<body>

<!-- before yield -->
<%= yield %>
<!-- after yeild -->

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
<table summary="Subject form fields">
	
	<tr>
		<th>Subject ID</th>
		<td><%= f.text_field :subject_id %></td>
	</tr>

	<tr>
		<th>Name</th>
		<td><%= f.text_field :name %></td>
	</tr>
	
	<tr>
		<th>Permalink</th>
		<td><%= f.text_field :permalink %></td>
	</tr>

	<tr>
		<th>Position</th>
		<td><%= f.text_field :position %></td>
	</tr>

	<tr>
		<th>Visible</th>
		<td><%= f.text_field :visible %></td>
	</tr>

</table>
<div class="form-buttons">
	</br>
	<%= f.submit("Submit") %>
</div> 

<% end %>

app/views/pages/edit.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="pages edit">
	<h2>Update Page</h2>
	<%= render(:partial => "form") %> 

</div>

app/views/pages/index.html.erb
<% @page_title ="Pages" %>
<div class="pages index">
	<h2>Pages</h2>

	<%= link_to("Add New page", {:action => 'new'}, :class => 'action new') %>

	<table class="listing" summary="page list">
		<tr class="header">
			<th>&nbsp;</th>
			<th>Subject ID</th>
			<th>Name</th>
			<th>Permalink</th>
			<th>Position</th>
			<th>Visible</th>
			<th>Actions</th>
		</tr>

		<% @pages.each do |page| %>

		<tr>
			<td><%= page.subject_id %></td>
			<td><%= page.name %></td>
			<td><%= page.permalink %></td>
			<td><%= page.position %></td>
			<td class="center"><%= status_tag(page.visible) %></td> 
			<!-- above is a ternary - a one line if/else statement -->
			<td class="center"><%#= page.sections.size %></td>
			<td class="actions">
				<%= link_to 'Show', page_path(page) %>
				<%= link_to 'Edit', edit_page_path(page) %>
				<%= button_to 'Delete subject', page, method: :delete %> 
              
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="pages new">
	<h2>Create a new page</h2>
	<%= render(:partial => "form") %> 

</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div class="pages show">
	<h2>Show Page</h2>

	<table summary="page detail view">
		
		<tr>
			<th>Subject ID</th>
			<td><%= @page.subject_id %></td>
		</tr>

		<tr>
			<th>Name</th>
			<td><%= @page.name %></td>
		</tr>

		<tr>
			<th>Permalink</th>
			<td><%= @page.permalink %></td>
		</tr>

		<tr>
			<th>Position</th>
			<td><%= @page.position%></td>
		</tr>

		<tr>
			<th>Visible</th>
			<td><%= @page.visible ? 'true' : 'false' %></td>
		</tr>

		<tr>
			<th>Created</th>
			<td><%= @page.created_at %><td>
		</tr>

		<tr>
			<th>Updated</th>
			<td><%= @page.updated_at %></td>
		</tr>

	</table>
</div>

app/views/sections/_form.html.erb
<%= form_for @section do |f| %>
<table summary="Subject form fields">
	
	<tr>
		<th>Page ID</th>
		<td><%= f.text_field :page_id %></td>
	</tr>

	<tr>
		<th>Name</th>
		<td><%= f.text_field :name %></td>
	</tr>

	<tr>
		<th>Position</th>
		<td><%= f.text_field :position %></td>
	</tr>

	<tr>
		<th>Visible</th>
		<td><%= f.text_field :visible %></td>
	</tr>

	<tr>
		<th>Content Type</th>
		<td><%= f.text_field :content_type %></td>
	</tr>

	<tr>
		<th>Content</th>
		<td><%= f.text_field :content %></td>
	</tr>

</table>
<div class="form-buttons">
	</br>
	<%= f.submit("Submit") %>
</div> 

<% end %>

app/views/sections/edit.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="sections edit">
	<h2>Update Section</h2>
	
	<%= render(:partial => "form") %> 

</div>

app/views/sections/index.html.erb
<% @page_title = "Sections" %>
<div class="sections index">
	<h2>Sections</h2>

	<%= link_to("Add New section", {:action => 'new'}, :class => 'action new') %>

	<table class="listing" summary="section list">
		<tr class="header">
			<th>&nbsp;</th>
			<th>Page ID</th>
			<th>Name</th>
			<th>Position</th>
			<th>Visible</th>
			<th>Content_Type</th>
			<th>Content</th>
			<th>Actions</th>
		</tr>

		<% @sections.each do |section| %>

		<tr>
			<td><%= section.page_id %></td>
			<td><%= section.name %></td>
			<td><%= section.position %></td>
			<td><%= section.visible %></td>
			<td><%= section.content_type %></td>
			<td><%= section.content %></td>
			<td class="center"><%= status_tag(section.visible) %></td> 
			<!-- above is a ternary - a one line if/else statement -->
			<td class="actions">
				<%= link_to 'Show', section_path(section) %>
				<%= link_to 'Edit', edit_section_path(section) %>
				<%= button_to 'Delete subject', section, method: :delete %> 
              
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="sections new">
	<h2>Create a New Section</h2>
	
	<%= render(:partial => "form") %> 

</div>

app/views/sections/show.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div class="subjects show">
	<h2>Show Section</h2>

	<table summary="Section detail view">
		<tr>
			<th>Page ID</th>
			<td><%= @section.page_id %></td>
		</tr>
		<tr>
			<th>Name</th>
			<td><%= @section.name %></td>
		</tr>

		<tr>
			<th>Position</th>
			<td><%= @section.position%></td>
		</tr>

		<tr>
			<th>Visible</th>
			<td><%= @section.visible ? 'true' : 'false' %></td>
		</tr>

		<tr>
			<th>Content Type</th>
			<td><%= @section.content_type %><td>
		</tr>

		<tr>
			<th>Content</th>
			<td><%= @section.content %><td>
		</tr>

		<tr>
			<th>Created</th>
			<td><%= @section.created_at %><td>
		</tr>

		<tr>
			<th>Updated</th>
			<td><%= @section.updated_at %></td>
		</tr>

	</table>
</div>

app/views/subjects/_form.html.erb
<%= form_for @subject do |f| %>
<table summary="Subject form fields">
	<tr>
		<th>Name</th>
		<td><%= f.text_field :name %></td>
	</tr>

	<tr>
		<th>Position</th>
		<td><%= f.text_field :position %></td>
	</tr>

	<tr>
		<th>Visible</th>
		<td><%= f.text_field :visible %></td>
	</tr>
</table>
<div class="form-buttons">
	</br>
	<%= f.submit("Submit") %>
</div> 

<% end %>

app/views/subjects/delete.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="subject delete">
	<h2>Delete Subject</h2>
	<p>Are you sure you want to permanently delete this subject?</p>

		<%= form_for @subject do |f| %>
		<p class="reference-name"><%= subject.name %></p>
		<div class="form-buttons">
		</br>
		<%= f.submit("Delete Subject") %>
		</div> 
		<% end %>

</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="subjects edit">
	<h2>Update Subject</h2>
	
<%= render(:partial => "form") %> 

</div>

app/views/subjects/index.html.erb
<% @page_title = "Subjects" %>
<div class="subjects index">
	<h2>Subjects</h2>

	<%= link_to("Add New Subject", {:action => 'new'}, :class => 'action new') %>
	<div><%= pluralize(@subjects.size, 'subject') %> found </div>

	<table class="listing" summary="Subject list">
		<tr class="header">
			<th>&nbsp;</th>
			<th>Subject</th>
			<th>Visible</th>
			<th>Pages</th>
			<th>Actions</th>
		</tr>

		<% @subjects.each do |subject| %>

		<tr class="<%= cycle('odd', 'even') %>">
			<td><%= subject.position %></td>
			<td><%= subject.name %></td>
			<td class="center"><%= status_tag(subject.visible) %></td> 

			<td class="center"><%= subject.pages.size %></td>
			<td class="actions">
				<%= link_to 'Show', subject_path(subject) %>
				<%= link_to 'Edit', edit_subject_path(subject) %>
				<%= button_to 'Delete subject', subject, method: :delete %> 
              
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div  class="subjects new">
	<h2>Create a new Subject</h2>

	 <%= render(:partial => "form") %> 

</div>
 

app/views/subjects/show.html.erb
<%= link_to("<< Back to list", {:action => 'index'}, :class => 'back-link')%>

<div class="subjects show">
	<h2>Show Subject</h2>

	<table summary="Subject detail view">
		<tr>
			<th>Name</th>
			<td><%= @subject.name %></td>
		</tr>

		<tr>
			<th>Position</th>
			<td><%= @subject.position%></td>
		</tr>

		<tr>
			<th>Visible</th>
			<td><%= @subject.visible ? 'true' : 'false' %></td>
		</tr>

		<tr>
			<th>Created</th>
			<td><%= @subject.created_at %><td>
		</tr>

		<tr>
			<th>Updated</th>
			<td><%= @subject.updated_at %></td>
		</tr>

	</table>
</div>